<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260514155619 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema: all tables, foreign keys, and indexes';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE modification_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, action VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, user_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B3AEEB2EA76ED395 ON modification_history (user_id)');
        $this->addSql('CREATE INDEX IDX_B3AEEB2E4584665A ON modification_history (product_id)');
        $this->addSql('CREATE TABLE operating_system (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, family VARCHAR(255) NOT NULL, version VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_name VARCHAR(255) NOT NULL, technical_name VARCHAR(255) NOT NULL, release_date DATE DEFAULT NULL, discontinued_year TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description TEXT DEFAULT NULL, original_price INT NOT NULL, sources TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, rejection_comment TEXT DEFAULT NULL, options JSON DEFAULT NULL, product_type_id INT NOT NULL, launch_os_id INT DEFAULT NULL, last_supported_os_id INT DEFAULT NULL, modified_by_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD14959723 ON product (product_type_id)');
        $this->addSql('CREATE INDEX IDX_D34A04ADA31B56C0 ON product (launch_os_id)');
        $this->addSql('CREATE INDEX IDX_D34A04ADA726F91F ON product (last_supported_os_id)');
        $this->addSql('CREATE INDEX IDX_D34A04ADDD5BE62E ON product (modified_by_user_id)');
        $this->addSql('CREATE INDEX IDX_PRODUCT_STATUS ON product (status)');
        $this->addSql('CREATE TABLE product_tag (product_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (product_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_E3A6E39C4584665A ON product_tag (product_id)');
        $this->addSql('CREATE INDEX IDX_E3A6E39CBAD26311 ON product_tag (tag_id)');
        $this->addSql('CREATE TABLE product_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(512) NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64617F034584665A ON product_image (product_id)');
        $this->addSql('CREATE TABLE product_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_389B7835E237E06 ON tag (name)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(256) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_UUID ON "user" (uuid)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE modification_history ADD CONSTRAINT FK_B3AEEB2EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE modification_history ADD CONSTRAINT FK_B3AEEB2E4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD14959723 FOREIGN KEY (product_type_id) REFERENCES product_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADA31B56C0 FOREIGN KEY (launch_os_id) REFERENCES operating_system (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADA726F91F FOREIGN KEY (last_supported_os_id) REFERENCES operating_system (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADDD5BE62E FOREIGN KEY (modified_by_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_tag ADD CONSTRAINT FK_E3A6E39C4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_tag ADD CONSTRAINT FK_E3A6E39CBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_image ADD CONSTRAINT FK_64617F034584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE modification_history DROP CONSTRAINT FK_B3AEEB2EA76ED395');
        $this->addSql('ALTER TABLE modification_history DROP CONSTRAINT FK_B3AEEB2E4584665A');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD14959723');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04ADA31B56C0');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04ADA726F91F');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04ADDD5BE62E');
        $this->addSql('ALTER TABLE product_tag DROP CONSTRAINT FK_E3A6E39C4584665A');
        $this->addSql('ALTER TABLE product_tag DROP CONSTRAINT FK_E3A6E39CBAD26311');
        $this->addSql('ALTER TABLE product_image DROP CONSTRAINT FK_64617F034584665A');
        $this->addSql('DROP INDEX IDX_PRODUCT_STATUS');
        $this->addSql('DROP TABLE modification_history');
        $this->addSql('DROP TABLE operating_system');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_tag');
        $this->addSql('DROP TABLE product_image');
        $this->addSql('DROP TABLE product_type');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
